apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgDEi3HCSS8tmi054fenRPI4AMlGpw8O7r0/sv4pL1LIGa23LwK5FiYlGVe1NW7hv4FC79guAZicgUoNZAP5vAHOgl0kxo1kNGdKPaAt4OhlS0WWv1D64dvTDKb6JssDQ2BrKdi7HOKv0tr2IRIjmD6k4Okq3gJwZNwnwVvByoS3LKosjk1UNKRJY5L5USsggon8EPtFvdWMv2gyLYVYHG49+Cku+j86v5dwgxPylnbFtoZALDgi6JkoByIZzNtGh/H7tpXNlLaVSSaFhrXb//ybgofhEEkZyRs2ilznqD6Aj7ZNMu1uAyxZPmuZOVxOzBoJ4Zn0I93L5k47p2fPPU+qvpueymjajj1rdXHKHCI/VDw/m1zfuFfALT3EMnrBu2auadPQRTjl963dACOgfqaEXLGqfLNyzT81YZ8Sa2BwcauTs+dDNxmAxPuUHy+INpvwLspeVEjiEAzmdyNt7rEL8IdjuzmIS2lRO4ifgS54miVaIQfips0i59sEVvYb5u3CTtmgDKuKP2G6VMnx9vNMtWGwmPwGAkG9rAgYGF0dqYBGTSseKEcdt6vmNmSg6bo+EOCyW7yMQYDC/8NZnhdC9nRZniahk8GZg4GIl0ssZC/zDlWL0CbHvhdo+6mcQxXPROYzGZVw5CPIBDRjAtgOThyX+C8k/JrhUG6PdIYSKVf+DAHBnGIPt8DlQRDKgBvq+ltvppm7Hw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

